name: auto-push-firefox

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install aiohttp aiofiles

    - name: Run python file
      run: |
        python firefox.py -y "${{ secrets.lzy_ylogin }}" -p "${{ secrets.lzy_phpdisk_info }}" -f "${{ secrets.lzy_folder_id }}"
