name: auto-push-firefox

on:
  schedule:
    - cron: "0 */2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and mod fenix
      run: |
        wget -q https://github.com/iBotPeaches/Apktool/releases/download/v2.5.0/apktool_2.5.0.jar
        
        ver=$(curl -sL https://api.github.com/repos/mozilla-mobile/fenix/releases/latest | sed 's/,/\n/g' | grep "tag_name" | sed 's/:/\n/g' | sed '1d' | sed 's/"//g' | sed 's/ v//g')
        #ver=$(curl -sL https://ftp.mozilla.org/pub/firefox/releases/ | grep "href" | sed 's/>/\n/g' | grep "/a" | sed 's/\//\n/g' | grep -v -E "<|[a-z]" | sort -t "." -k 1nr -k 2nr -k 3nr | head -n 1)
        wget -q https://github.com/mozilla-mobile/fenix/releases/download/v${ver}/fenix-${ver}-armeabi-v7a.apk
        wget -q https://github.com/mozilla-mobile/fenix/releases/download/v${ver}/fenix-${ver}-arm64-v8a.apk
        
        java -jar apktool_2.5.0.jar d fenix-${ver}-armeabi-v7a.apk -o v7a
        java -jar apktool_2.5.0.jar d fenix-${ver}-arm64-v8a.apk -o v8a
        sed -i 's/baidu/unknown/g' v7a/assets/extensions/webcompat/data/ua_overrides.js
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/' v7a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's/browser.safebrowsing.phishing.enabled/unknown/' v7a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's#iget-boolean v0, p0, Lorg/mozilla/fenix/utils/Settings;->showSecretDebugMenuThisSession:Z#const/4 v0, 0x1#' v7a/smali_classes2/org/mozilla/fenix/utils/Settings.smali
        sed -i '/aboutConfigEnabled/{n;s#.locals 1#.locals 1\n    const/4 p1, 0x1#}' v7a/smali_classes2/org/mozilla/geckoview/GeckoRuntimeSettings\$Builder.smali
        sed -i '1,/const\/4 v0, 0x0/{s#const/4 v0, 0x0#const/4 v0, 0x1#}' v7a/smali_classes2/org/mozilla/fenix/ReleaseChannel.smali
        
        sed -i 's/baidu/unknown/g' v8a/assets/extensions/webcompat/data/ua_overrides.js
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/' v8a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's/browser.safebrowsing.phishing.enabled/unknown/' v8a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's#iget-boolean v0, p0, Lorg/mozilla/fenix/utils/Settings;->showSecretDebugMenuThisSession:Z#const/4 v0, 0x1#' v8a/smali_classes2/org/mozilla/fenix/utils/Settings.smali
        sed -i '/aboutConfigEnabled/{n;s#.locals 1#.locals 1\n    const/4 p1, 0x1#}' v8a/smali_classes2/org/mozilla/geckoview/GeckoRuntimeSettings\$Builder.smali
        sed -i '1,/const\/4 v0, 0x0/{s#const/4 v0, 0x0#const/4 v0, 0x1#}' v8a/smali_classes2/org/mozilla/fenix/ReleaseChannel.smali
        
        java -jar apktool_2.5.0.jar b v7a -o v7a.apk --use-aapt2
        java -jar apktool_2.5.0.jar b v8a -o v8a.apk --use-aapt2
        
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jar
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jks
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out fenix-${ver}-armeabi-v7a-mod.apk v7a.apk
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out fenix-${ver}-arm64-v8a-mod.apk v8a.apk

    - name: Install dependencies
      run: |
        pip install lanzou-api
        
    - name: Create python file
      run: |
        cat > firefox.py << EOF
        import urllib, json, re
        from lanzou.api import LanZouCloud
        resp = urllib.request.urlopen("https://ftp.mozilla.org/pub/firefox/releases/")
        resp = resp.read().decode()
        resp1 = re.findall(r'(?<=">)\d+\.\d+(?=/<)', resp)
        resp1.sort(key=lambda x: (int(x.split(".")[0]), int(x.split(".")[1])))
        resp1 = resp1[-1]
        resp2 = re.findall(r'(?<=">)\d+\.\d+\.\d+(?=/<)', resp)
        resp2.sort(key=lambda x: (int(x.split(".")[0]), int(x.split(".")[1]), int(x.split(".")[2])))
        resp2 = resp2[-1]
        if resp1.split(".")[0] == resp2.split(".")[0]:
            resp = resp2
        else:
            resp = resp1
        url32 = "https://ftp.mozilla.org/pub/firefox/releases/" + resp + "/win32/zh-CN/Firefox%20Setup%20" + resp + ".exe"
        url64 = "https://ftp.mozilla.org/pub/firefox/releases/" + resp + "/win64/zh-CN/Firefox%20Setup%20" + resp + ".exe"
        resp32 = "firefox-" + resp + "-win32.exe"
        resp64 = "firefox-" + resp + "-win64.exe"
        resp = urllib.request.urlopen("https://api.github.com/repos/mozilla-mobile/fenix/releases/latest")
        resp = json.loads(resp.read().decode())["tag_name"].replace("v", "")
        resp32m = "fenix-" + resp + "-armeabi-v7a.apk"
        resp64m = "fenix-" + resp + "-arm64-v8a.apk"
        resp32mm = "fenix-" + resp + "-armeabi-v7a-mod.apk"
        resp64mm = "fenix-" + resp + "-arm64-v8a-mod.apk"
        lzy = LanZouCloud()
        cookie = {'ylogin': '${{ secrets.lzy_ylogin }}', 'phpdisk_info': '${{ secrets.lzy_phpdisk_info }}'}
        if lzy.login_by_cookie(cookie) == LanZouCloud.SUCCESS:
            files = lzy.get_file_list(${{ secrets.lzy_folder_id }})
            if files.find_by_name(resp32) is None:
                urllib.request.urlretrieve(url32, resp32)
                lzy.upload_file(resp32, ${{ secrets.lzy_folder_id }})
            if files.find_by_name(resp64) is None:
                urllib.request.urlretrieve(url64, resp64)
                lzy.upload_file(resp64, ${{ secrets.lzy_folder_id }})
            if resp.find("rc") == -1:
                if files.find_by_name(resp32m) is None:
                    lzy.upload_file(resp32m, ${{ secrets.lzy_folder_id }})
                if files.find_by_name(resp64m) is None:
                    lzy.upload_file(resp64m, ${{ secrets.lzy_folder_id }})
                if files.find_by_name(resp32mm) is None:
                    lzy.upload_file(resp32mm, ${{ secrets.lzy_folder_id }})
                if files.find_by_name(resp64mm) is None:
                    lzy.upload_file(resp64mm, ${{ secrets.lzy_folder_id }})
        EOF
        
    - name: Run python file
      run: |
        python firefox.py
