name: auto-mod-fenix

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and mod fenix
      run: |
        cat > mobile.sh << EOF
        wget -q -O "apktool.jar" https://github.com/iBotPeaches/Apktool/releases/download/v2.6.0/apktool_2.6.0.jar
        
        wget -q -O "resp32m" url32m
        wget -q -O "resp64m" url64m
        
        java -jar apktool.jar d resp32m -o v7a
        java -jar apktool.jar d resp64m -o v8a

        sed -i "s/^.*versionCode.*$/  versionCode: '2147483647'/" v7a/apktool.yml
        sed -i 's/baidu/unknown/g' v7a/assets/extensions/webcompat/data/ua_overrides.js
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v7a/smali_classes2/org/mozilla/geckoview/ContentBlocking\\\$Settings.smali
        sed -i '/public aboutConfigEnabled/{n;s/\.locals 1/\.locals 1\n    const\/4 p1, 0x1/}' v7a/smali_classes2/org/mozilla/geckoview/GeckoRuntimeSettings\\\$Builder.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/;/invoke-virtual {p0, p1, p2, p3}/i\    const\/4 p2, 0x1' v7a/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v7a/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/const\/4 v0, 0x0/const\/4 v0, 0x1/g' v7a/smali_classes2/org/mozilla/fenix/ReleaseChannel.smali
        sed -i 's/"mozilla"/"lindongbin"/g;s/7dfae8669acc4312a65e8ba5553036/fenix/g' v7a/smali_classes2/org/mozilla/fenix/components/Components\\\$addonCollectionProvider\\\$2.smali
        sed -i 's/"-popularity"/"name"/' v7a/smali/mozilla/components/feature/addons/amo/SortOption.smali
        
        sed -i "s/^.*versionCode.*$/  versionCode: '2147483647'/" v8a/apktool.yml
        sed -i 's/baidu/unknown/g' v8a/assets/extensions/webcompat/data/ua_overrides.js
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v8a/smali_classes2/org/mozilla/geckoview/ContentBlocking\\\$Settings.smali
        sed -i '/public aboutConfigEnabled/{n;s/\.locals 1/\.locals 1\n    const\/4 p1, 0x1/}' v8a/smali_classes2/org/mozilla/geckoview/GeckoRuntimeSettings\\\$Builder.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/;/invoke-virtual {p0, p1, p2, p3}/i\    const\/4 p2, 0x1' v8a/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v8a/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/const\/4 v0, 0x0/const\/4 v0, 0x1/g' v8a/smali_classes2/org/mozilla/fenix/ReleaseChannel.smali
        sed -i 's/"mozilla"/"lindongbin"/g;s/7dfae8669acc4312a65e8ba5553036/fenix/g' v8a/smali_classes2/org/mozilla/fenix/components/Components\\\$addonCollectionProvider\\\$2.smali
        sed -i 's/"-popularity"/"name"/' v8a/smali/mozilla/components/feature/addons/amo/SortOption.smali
        
        java -jar apktool.jar b v7a -o v7a.apk --use-aapt2
        java -jar apktool.jar b v8a -o v8a.apk --use-aapt2
        
        wget -q https://github.com/lindongbin/gt/raw/master/zipalign
        wget -q -P ./lib64 https://github.com/lindongbin/gt/raw/master/libc%2B%2B.so
        chmod +x zipalign
        ./zipalign -p 4 v7a.apk v7a-align.apk
        ./zipalign -p 4 v8a.apk v8a-align.apk
        
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jar
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jks
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out resp32mm v7a-align.apk
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out resp64mm v8a-align.apk
        EOF

        chmod +x ./mobile.sh

    - name: Install dependencies
      run: |
        pip install aiohttp
        
    - name: Create python file
      run: |
        cat > fenix.py << EOF
        import asyncio, aiohttp, json, re, os
        async def upload(filename):
            cookies = {'ylogin': '${{ secrets.lzy_ylogin }}', 'phpdisk_info': '${{ secrets.lzy_phpdisk_info }}'}
            headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0'}
            url = "https://pc.woozooo.com/fileup.php"
            fields={"task": "1", "folder_id": "${{ secrets.lzy_folder_id }}", "id": "WU_FILE_0", "name": filename, "type": "application/octet-stream"}
            with aiohttp.MultipartWriter("form-data") as mpwriter:
                part = mpwriter.append(open(filename, 'rb'))
                part.set_content_disposition('form-data', name="upload_file", filename=filename, quote_fields=False)
                for key, value in fields.items():
                  part = mpwriter.append(value)
                  part.set_content_disposition('form-data', name=key)
                headers["Content-Type"] = mpwriter.content_type
            async with aiohttp.ClientSession() as session:
                async with session.post(url=url, headers=headers, data=mpwriter, cookies=cookies, timeout=0) as req:
                    resp = await req.read()
                    resp = json.loads(resp)["info"]
                    print(filename + resp)
        async def main():
            cookies = {'ylogin': '${{ secrets.lzy_ylogin }}', 'phpdisk_info': '${{ secrets.lzy_phpdisk_info }}'}
            headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0'}
            url = "https://pc.woozooo.com/doupload.php"
            data = {'task': 5, 'folder_id': ${{ secrets.lzy_folder_id }}, 'pg': 1}
            async with aiohttp.ClientSession() as session:
                async with session.post(url=url, data=data, headers=headers, cookies=cookies) as req:
                    files = await req.text()
                    files = files.encode('utf-8').decode('unicode_escape')
                url = "https://api.github.com/repos/mozilla-mobile/fenix/releases/latest"
                async with session.get(url=url) as req:
                    resp = await req.read()
                resp = json.loads(resp)["tag_name"].replace("v", "")
                url32m = "https://github.com/mozilla-mobile/fenix/releases/download/v" + resp + "/fenix-" + resp + "-armeabi-v7a.apk"
                url64m = "https://github.com/mozilla-mobile/fenix/releases/download/v" + resp + "/fenix-" + resp + "-arm64-v8a.apk"
                resp32m = "fenix-" + resp + "-armeabi-v7a.apk"
                resp64m = "fenix-" + resp + "-arm64-v8a.apk"
                resp32mm = "fenix-" + resp + "-armeabi-v7a-自定义扩展集合.apk"
                resp64mm = "fenix-" + resp + "-arm64-v8a-自定义扩展集合.apk"
                if files.find(resp32mm) == -1 or files.find(resp64mm) == -1:
                    with open('mobile.sh','+r') as f:
                        t = f.read()
                        t = t.replace('url32m', url32m).replace('url64m', url64m).replace('resp32mm', resp32mm).replace('resp64mm', resp64mm).replace('resp32m', resp32m).replace('resp64m', resp64m)
                        f.seek(0, 0)
                        f.write(t)
                    os.system("./mobile.sh")
                if files.find(resp32mm) == -1:
                    await upload(resp32mm)
                else:
                    print(resp32mm + "已存在")
                if files.find(resp64mm) == -1:
                    await upload(resp64mm)
                else:
                    print(resp64mm + "已存在")
        asyncio.get_event_loop().run_until_complete(main())
        EOF
        
    - name: Run python file
      run: |
        python fenix.py
