name: auto-push-whitelist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install urllib3 certifi

    - name: Run python file
      run: |
        python whitelist.py
        
    - name: Commit files
      run: |
        git config user.name lindongbin
        git config user.email lin.crk@gmail.com
        git checkout --orphan whitelist
        git rm -rf .
        git add "chinalist.pac"
        git commit -m "Update chinalist.pac"
        git push --force origin whitelist:whitelist
