name: auto-push-firefox

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and mod fenix
      run: |
        cat > firefox.sh << EOF
        wget -q -O "resp32" url32
        wget -q -O "resp64" url64
        EOF

        chmod +x ./firefox.sh

        cat > mobile.sh << EOF
        wget -q https://github.com/iBotPeaches/Apktool/releases/download/v2.5.0/apktool_2.5.0.jar
        
        wget -q url32m
        wget -q url64m
        
        java -jar apktool_2.5.0.jar d resp32m -o v7a
        java -jar apktool_2.5.0.jar d resp64m -o v8a
        
        sed -i "s/^.*versionCode.*$/  versionCode: '2147483647'/" v7a/apktool.yml
        sed -i 's/baidu/unknown/g' v7a/assets/extensions/webcompat/data/ua_overrides.js
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v7a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i '/public aboutConfigEnabled/{n;s/\.locals 1/\.locals 1\n    const\/4 p1, 0x1/}' v7a/smali_classes2/org/mozilla/geckoview/GeckoRuntimeSettings\$Builder.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/;/invoke-virtual {p0, p1, p2, p3}/i\    const\/4 p2, 0x1' v7a/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i 's/android\/downloads/([^\\\\\\\\s]+)\/downloads/;/getOrNull/i\    const\/4 v5, 0x2' v7a/smali_classes2/org/mozilla/fenix/AppRequestInterceptor.smali
        sed -i 's/if-eqz p1, :cond_a/goto :cond_a/' v7a/smali/mozilla/components/feature/addons/ui/AddonsManagerAdapter.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v7a/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/0xb40/0x5a0/g' v7a/smali_classes2/org/mozilla/fenix/components/Components\$addonCollectionProvider\$2.smali
        sed -i '/invoke-direct\/range {v1 \.\. v11}/i\
            new-instance v1, Ljava\/lang\/StringBuilder;\
            invoke-direct {v1}, Ljava\/lang\/StringBuilder;-><init>()V\
            const-string v2, "https:\/\/cdn.jsdelivr.net\/gh\/lindongbin\/gt@addons\/addons\.json?t="\
            invoke-virtual {v1, v2}, Ljava\/lang\/StringBuilder;->append(Ljava\/lang\/String;)Ljava\/lang\/StringBuilder;\
            new-instance v2, Ljava\/util\/Date;\
            invoke-direct {v2}, Ljava\/util\/Date;-><init>()V\
            invoke-virtual {v2}, Ljava\/util\/Date;->getTime()J\
            move-result-wide v2\
            invoke-static {v2, v3}, Ljava\/lang\/String;->valueOf(J)Ljava\/lang\/String;\
            move-result-object v2\
            invoke-virtual {v1, v2}, Ljava\/lang\/StringBuilder;->append(Ljava\/lang\/String;)Ljava\/lang\/StringBuilder;\
            invoke-virtual {v1}, Ljava\/lang\/StringBuilder;->toString()Ljava\/lang\/String;\
            move-result-object v2\
            const\/4 v3, 0x0\
            move-object v1, v12' v7a/smali/mozilla/components/feature/addons/amo/AddonCollectionProvider.smali
        
        sed -i "s/^.*versionCode.*$/  versionCode: '2147483647'/" v8a/apktool.yml
        sed -i 's/baidu/unknown/g' v8a/assets/extensions/webcompat/data/ua_overrides.js
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v8a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i '/public aboutConfigEnabled/{n;s/\.locals 1/\.locals 1\n    const\/4 p1, 0x1/}' v8a/smali_classes2/org/mozilla/geckoview/GeckoRuntimeSettings\$Builder.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/;/invoke-virtual {p0, p1, p2, p3}/i\    const\/4 p2, 0x1' v8a/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i 's/android\/downloads/([^\\\\\\\\s]+)\/downloads/;/getOrNull/i\    const\/4 v5, 0x2' v8a/smali_classes2/org/mozilla/fenix/AppRequestInterceptor.smali
        sed -i 's/if-eqz p1, :cond_a/goto :cond_a/' v8a/smali/mozilla/components/feature/addons/ui/AddonsManagerAdapter.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v8a/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/0xb40/0x5a0/g' v8a/smali_classes2/org/mozilla/fenix/components/Components\$addonCollectionProvider\$2.smali
        sed -i '/invoke-direct\/range {v1 \.\. v11}/i\
            new-instance v1, Ljava\/lang\/StringBuilder;\
            invoke-direct {v1}, Ljava\/lang\/StringBuilder;-><init>()V\
            const-string v2, "https:\/\/cdn.jsdelivr.net\/gh\/lindongbin\/gt@addons\/addons\.json?t="\
            invoke-virtual {v1, v2}, Ljava\/lang\/StringBuilder;->append(Ljava\/lang\/String;)Ljava\/lang\/StringBuilder;\
            new-instance v2, Ljava\/util\/Date;\
            invoke-direct {v2}, Ljava\/util\/Date;-><init>()V\
            invoke-virtual {v2}, Ljava\/util\/Date;->getTime()J\
            move-result-wide v2\
            invoke-static {v2, v3}, Ljava\/lang\/String;->valueOf(J)Ljava\/lang\/String;\
            move-result-object v2\
            invoke-virtual {v1, v2}, Ljava\/lang\/StringBuilder;->append(Ljava\/lang\/String;)Ljava\/lang\/StringBuilder;\
            invoke-virtual {v1}, Ljava\/lang\/StringBuilder;->toString()Ljava\/lang\/String;\
            move-result-object v2\
            const\/4 v3, 0x0\
            move-object v1, v12' v8a/smali/mozilla/components/feature/addons/amo/AddonCollectionProvider.smali
        
        java -jar apktool_2.5.0.jar b v7a -o v7a.apk --use-aapt2
        java -jar apktool_2.5.0.jar b v8a -o v8a.apk --use-aapt2
        
        wget -q https://github.com/lindongbin/gt/raw/master/zipalign
        wget -q -P ./lib64 https://github.com/lindongbin/gt/raw/master/libc%2B%2B.so
        chmod +x zipalign
        ./zipalign -p 4 v7a.apk v7a-align.apk
        ./zipalign -p 4 v8a.apk v8a-align.apk
        
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jar
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jks
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out resp32mm v7a-align.apk
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out resp64mm v8a-align.apk
        EOF

        chmod +x ./mobile.sh

    - name: Install dependencies
      run: |
        pip install aiohttp
        
    - name: Create python file
      run: |
        cat > firefox.py << EOF
        import asyncio, aiohttp, json, re, os
        async def upload(filename):
            cookies = {'ylogin': '${{ secrets.lzy_ylogin }}', 'phpdisk_info': '${{ secrets.lzy_phpdisk_info }}'}
            headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0'}
            url = "https://pc.woozooo.com/fileup.php"
            fields={"task": "1", "folder_id": "${{ secrets.lzy_folder_id }}", "id": "WU_FILE_0", "name": filename, "type": "application/octet-stream"}
            with aiohttp.MultipartWriter("form-data") as mpwriter:
                part = mpwriter.append(open(filename, 'rb'))
                part.set_content_disposition('form-data', name="upload_file", filename=filename)
                for key, value in fields.items():
                  part = mpwriter.append(value)
                  part.set_content_disposition('form-data', name=key)
                headers["Content-Type"] = mpwriter.content_type
            async with aiohttp.ClientSession() as session:
                async with session.post(url=url, headers=headers, data=mpwriter, cookies=cookies, timeout=0) as req:
                    resp = await req.read()
                    resp = json.loads(resp)["info"]
                    print(filename + resp)
        async def main():
            cookies = {'ylogin': '${{ secrets.lzy_ylogin }}', 'phpdisk_info': '${{ secrets.lzy_phpdisk_info }}'}
            headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0'}
            url = "https://pc.woozooo.com/doupload.php"
            data = {'task': 5, 'folder_id': ${{ secrets.lzy_folder_id }}, 'pg': 1}
            async with aiohttp.ClientSession() as session:
                async with session.post(url=url, data=data, headers=headers, cookies=cookies) as req:
                    files = await req.text()
                url = "https://ftp.mozilla.org/pub/firefox/releases/"
                async with session.get(url=url) as req:
                    resp = await req.text()
                resp1 = re.findall(r'(?<=">)\d+\.\d+(?=/<)', resp)
                resp1.sort(key=lambda x: (int(x.split(".")[0]), int(x.split(".")[1])))
                resp1 = resp1[-1]
                resp2 = re.findall(r'(?<=">)\d+\.\d+\.\d+(?=/<)', resp)
                resp2.sort(key=lambda x: (int(x.split(".")[0]), int(x.split(".")[1]), int(x.split(".")[2])))
                resp2 = resp2[-1]
                if resp1.split(".")[0] == resp2.split(".")[0]:
                    resp = resp2
                else:
                    resp = resp1
                url32 = "https://ftp.mozilla.org/pub/firefox/releases/" + resp + "/win32/zh-CN/Firefox%20Setup%20" + resp + ".exe"
                url64 = "https://ftp.mozilla.org/pub/firefox/releases/" + resp + "/win64/zh-CN/Firefox%20Setup%20" + resp + ".exe"
                resp32 = "firefox-" + resp + "-win32.exe"
                resp64 = "firefox-" + resp + "-win64.exe"
                if files.find(resp32) == -1 or files.find(resp64) == -1:
                    with open('firefox.sh','+r') as f:
                        t = f.read()
                        t = t.replace('url32', url32).replace('url64', url64).replace('resp32', resp32).replace('resp64', resp64)
                        f.seek(0, 0)
                        f.write(t)
                    os.system("./firefox.sh")
                if files.find(resp32) == -1:
                    await upload(resp32)
                else:
                    print(resp32 + "已存在")
                if files.find(resp64) == -1:
                    await upload(resp64)
                else:
                    print(resp64 + "已存在")
                url = "https://api.github.com/repos/mozilla-mobile/fenix/releases/latest"
                async with session.get(url=url) as req:
                    resp = await req.read()
                resp = json.loads(resp)["tag_name"].replace("v", "")
                if resp.find("rc") == -1:
                    url32m = "https://github.com/mozilla-mobile/fenix/releases/download/v" + resp + "/fenix-" + resp + "-armeabi-v7a.apk"
                    url64m = "https://github.com/mozilla-mobile/fenix/releases/download/v" + resp + "/fenix-" + resp + "-arm64-v8a.apk"
                    resp32m = "fenix-" + resp + "-armeabi-v7a.apk"
                    resp64m = "fenix-" + resp + "-arm64-v8a.apk"
                    resp32mm = "fenix-" + resp + "-armeabi-v7a-mod.apk"
                    resp64mm = "fenix-" + resp + "-arm64-v8a-mod.apk"
                    if files.find(resp32m) == -1 or files.find(resp64m) == -1 or files.find(resp32mm) == -1 or files.find(resp64mm) == -1:
                        with open('mobile.sh','+r') as f:
                            t = f.read()
                            t = t.replace('url32m', url32m).replace('url64m', url64m).replace('resp32mm', resp32mm).replace('resp64mm', resp64mm).replace('resp32m', resp32m).replace('resp64m', resp64m)
                            f.seek(0, 0)
                            f.write(t)
                        os.system("./mobile.sh")
                    if files.find(resp32m) == -1:
                        await upload(resp32m)
                    else:
                        print(resp32m + "已存在")
                    if files.find(resp64m) == -1:
                        await upload(resp64m)
                    else:
                        print(resp64m + "已存在")
                    if files.find(resp32mm) == -1:
                        await upload(resp32mm)
                    else:
                        print(resp32mm + "已存在")
                    if files.find(resp64mm) == -1:
                        await upload(resp64mm)
                    else:
                        print(resp64mm + "已存在")
        asyncio.get_event_loop().run_until_complete(main())
        EOF
        
    - name: Run python file
      run: |
        python firefox.py
