name: auto-push-firefox

on:
  schedule:
    - cron: "0 0 * * 2-4"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install lanzou-api
        
    - name: Create python file
      run: |
        cat > firefox.py << EOF
        import urllib, json
        from lanzou.api import LanZouCloud
        resp = urllib.request.urlopen("https://product-details.mozilla.org/1.0/firefox_versions.json")
        resp = json.loads(resp.read().decode())["LATEST_FIREFOX_VERSION"]
        url32 = "https://ftp.mozilla.org/pub/firefox/releases/" + resp + "/win32/zh-CN/Firefox%20Setup%20" + resp + ".exe"
        url64 = "https://ftp.mozilla.org/pub/firefox/releases/" + resp + "/win64/zh-CN/Firefox%20Setup%20" + resp + ".exe"
        resp32 = "firefox-" + resp + "-win32.exe"
        resp64 = "firefox-" + resp + "-win64.exe"
        lzy = LanZouCloud()
        cookie = {'ylogin': '${{ secrets.lzy_ylogin }}', 'phpdisk_info': '${{ secrets.lzy_phpdisk_info }}'}
        if lzy.login_by_cookie(cookie) == LanZouCloud.SUCCESS:
            files = lzy.get_file_list(${{ secrets.lzy_folder_id }})
            if files.find_by_name(resp32) is None:
                urllib.request.urlretrieve(url32, resp32)
                lzy.upload_file(resp32, ${{ secrets.lzy_folder_id }})
            if files.find_by_name(resp64) is None:
                urllib.request.urlretrieve(url64, resp64)
                lzy.upload_file(resp64, ${{ secrets.lzy_folder_id }})
        EOF
        
    - name: Run python file
      run: |
        python firefox.py
