name: euserv-auto-extend

on:
  schedule:
    - cron: "0 0 * * 0,6"

jobs:
  extend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install aiohttp
        
    - name: Create python file
      run: |
        cat > euserv.py << EOF
        import asyncio, aiohttp, re
        async def main():
            async with aiohttp.ClientSession() as session:
                email = "${{ secrets.eu_username }}"
                password = "${{ secrets.eu_password }}"
                url = "https://support.euserv.com/index.iphp"
                headers = {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"}
                data = {
                    "email": email,
                    "password": password,
                    "form_selected_language": "en",
                    "Submit": "Login",
                    "subaction": "login"
                }
                async with session.post(url=url, headers = headers, data=data) as req:
                    resp = await req.text()
                    sess_id = re.findall(r'"sess_id" value="(.*?)"', resp)[0]
                    ord_no = re.findall(r'"ord_no" value="(.*?)"', resp)[0]
                data = {
                    "Submit": "Extend contract",
                    "sess_id": sess_id,
                    "ord_no": ord_no,
                    "subaction": "choose_order",
                    "choose_order_subaction": "show_contract_details"
                }
                async with session.post(url=url, headers = headers, data=data) as req:
                    resp = await req.text()
                data = {
                    "sess_id": sess_id,
                    "subaction": "kc2_security_password_get_token",
                    "prefix": "kc2_customer_contract_details_extend_contract_",
                    "password": password
                }
                async with session.post(url=url, headers = headers, data=data) as req:
                    resp = await req.json()
                    token = resp["token"]["value"]
                data = {
                    "sess_id": sess_id,
                    "ord_id": ord_no,
                    "subaction": "kc2_customer_contract_details_extend_contract_term",
                    "token": token
                }
                async with session.post(url=url, headers = headers, data=data) as req:
                    resp = await req.text()
                    if resp.find("Thank you! The contract has been extended.") > -1:
                        print("续期成功")
                    elif resp.find("Error: Manual contract extension is not possible at the moment.") > -1:
                        print("无需续期")
                    else:
                        print("状态未知")
        asyncio.get_event_loop().run_until_complete(main())
        EOF

    - name: Run python file
      run: |
        python euserv.py
